# NumPy
It stands for numerical Python, it will provide lot of built-in functions to work in a domain of Linear Algebra, Fourier Transform and Matrices. Mainly it provides functions related to arrays. It creats an Array called ndarray(n dimention array). The working of ndarray is faster than lists. Most of the part of Numpy was created in C&C++. It gives a high performance computing of arrays.
* To get the version of Numpy [print(numpy.__version__)]

In [4]:
import numpy as np
print(np.version)
print(np.__version__)

<module 'numpy.version' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>
1.21.5


Creating of ndarray
* Firstly we have to import numpy.
* we have to use array() function with argumants as lists or tuples.[array(list/tuple)]

In [1]:
import numpy

a = numpy.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
import numpy

a = numpy.array((1,2,3))
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
import numpy as np #alias name

a = np.array([1,2,3])
print(a)

[1 2 3]


0-D Array
*  contains only one element.

In [18]:
a=np.array(54)
print(a)

54


1-D Array
* It is nothing of array of 0-D elements

In [8]:
b= np.array([1,2,3])
print(b)

[1 2 3]


2-D array
* it is array of 1-D arrays

In [10]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


3-D arrays
* array of 2-D arrays

In [12]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


To find the dimension(level of depth of array). Using [ndim] it will give us the dimension of a array. and [type()] will tell us which type of object assigned to a variable.

In [19]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
print(type(a))
print(type(d))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
