where() -> returns index of given value.

In [1]:
import numpy as np

In [2]:
a = np.arange(10,100,10)
print(a)

[10 20 30 40 50 60 70 80 90]


In [3]:
np.where(a==40)

(array([3], dtype=int64),)

In [4]:
np.where(a%3 == 0)

(array([2, 5, 8], dtype=int64),)

In [8]:
a = np.array([10,10,20,30,10,40])
np.where(a == 10)

(array([0, 1, 4], dtype=int64),)

searchsorted() -> returns the index where the specified value should be inserted
               -> elements should be in sorted order

In [9]:
a = np.arange(10,100,10)
print(a)

[10 20 30 40 50 60 70 80 90]


In [10]:
np.searchsorted(a,45)

4

In [11]:
np.searchsorted(a,[15,45,46])

array([1, 4, 4], dtype=int64)