In [1]:
import numpy as np

In [2]:
a = np.array([50,40,10,20,30])
print(a)

[50 40 10 20 30]


In [3]:
np.sort(a)

array([10, 20, 30, 40, 50])

In [4]:
b = np.array([[50,40,30],[20,10,90]])
print(b)

np.sort(b)

[[50 40 30]
 [20 10 90]]


array([[30, 40, 50],
       [10, 20, 90]])

In [5]:
np.sort(b,axis=0)

array([[20, 10, 30],
       [50, 40, 90]])

In [6]:
np.sort(b,axis=1)

array([[30, 40, 50],
       [10, 20, 90]])

In [9]:
d = np.dtype([('name','S10'),('perc',float)])

stud = np.array([('abc',90.3),('def',95.3),('ghi',65.4)])
print(stud)
print('')
stud1 = np.array([('abc',90.3),('def',95.3),('ghi',65.4)],dtype=d)
print(stud1)


[['abc' '90.3']
 ['def' '95.3']
 ['ghi' '65.4']]

[(b'abc', 90.3) (b'def', 95.3) (b'ghi', 65.4)]


In [15]:
np.sort(stud,order='perc')# it will through an error if we will not mention datatype while sorting using order

ValueError: Cannot specify order when the array has no fields.

In [12]:
np.sort(stud1,order='perc')

array([(b'ghi', 65.4), (b'abc', 90.3), (b'def', 95.3)],
      dtype=[('name', 'S10'), ('perc', '<f8')])

In [14]:
np.sort(stud1,order='name')

array([(b'abc', 90.3), (b'def', 95.3), (b'ghi', 65.4)],
      dtype=[('name', 'S10'), ('perc', '<f8')])