amin()

* minimum element. We can achive it through axis=0, axis=1, complete array.

In [2]:
import numpy as np

In [3]:
a = np.array([[10,20,30],[50,70,80],[1,2,3]])
print(a)

[[10 20 30]
 [50 70 80]
 [ 1  2  3]]


In [4]:
np.amin(a)

1

In [7]:
np.amin(a,axis=0)

array([1, 2, 3])

In [8]:
np.amin(a,axis=1)

array([10, 50,  1])

amax()

* maximun element. We can achive it through axis=0, axis=1, complete array

In [5]:
np.amax(a)

80

In [9]:
np.amax(a,axis=0)

array([50, 70, 80])

In [10]:
np.amax(a,axis=1)

array([30, 80,  3])

average()

* average. We can achive it through complete array, weighted average

In [11]:
np.average(a)

29.555555555555557

In [12]:
weighted = [1,2,3]

np.average(a,weights=weighted,axis=0)

array([18.83333333, 27.66666667, 33.16666667])

In [13]:
np.average(a,weights=weighted,axis=1)

array([23.33333333, 71.66666667,  2.33333333])

mean()

In [15]:
np.mean(a)# same as averages

29.555555555555557

In [16]:
np.mean(a,axis=0)

array([20.33333333, 30.66666667, 37.66666667])

In [17]:
np.mean(a,axis=1)

array([20.        , 66.66666667,  2.        ])

median()

In [19]:
np.median(a) # first it will convert into sorded order and will return center element.

20.0

In [20]:
np.median(a,axis=0)

array([10., 20., 30.])

In [21]:
np.median(a,axis=1)

array([20., 70.,  2.])

var() -> variance

In [22]:
np.var(a)

816.9135802469136

std() -> standard deviation

In [23]:
np.std(a)

28.5817000937123