# Arrays with Existing Data

    * ASARROY()
    * FROMBUFFER()
    * FROMITER()

-------------------
difference between list and array.

* lisat = [10,20,'abc']
* array = [10 20 abc]

-------------------

asarray(input, dtype, order)
---------------------------------------

* input = list, tuple, any combination
* dtype = int, str, float
* order(not mandarory) -> Row Major - 'C' (default)
                       -> Column Major - 'F'  


In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
b = np.array([[10,20,30],[40,50,60]])#multi dimentional array.
print(b)

[[10 20 30]
 [40 50 60]]


In [3]:
res = np.asarray(a,dtype = 'float',order = "C")
print(res)

[1. 2. 3. 4. 5.]


In [7]:
res1 = np.asarray(b,dtype = 'int',order = 'C')
print(res1)

[[10 20 30]
 [40 50 60]]


In [9]:
for i in np.nditer(res1):
    print(i)

10
20
30
40
50
60


In [8]:
res2 = np.asarray(b,dtype = 'int',order = 'F')
print(res2)

[[10 20 30]
 [40 50 60]]


In [10]:
for i in np.nditer(res2):
    print(i)

10
40
20
50
30
60


frombuffer(buffer, dtype, count, offser)
-------------------------------------------------------

* create an array with given datatype of give length from given position

* count = -1 by default (length of array)
* offset = 0 by default (start index)

In [12]:
s = b"hello welcome to python" # purpose of usint 'b' is to store the data in form of bytes(ASCI) not in form of string.

print(s)

b'hello welcome to python'


In [13]:
c = np.frombuffer(s,dtype='S1',count=-1,offset=0)
print(c)

[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'e' b'l' b'c' b'o' b'm' b'e' b' '
 b't' b'o' b' ' b'p' b'y' b't' b'h' b'o' b'n']


In [14]:
c = np.frombuffer(s,dtype='S1',count=10,offset=0)
print(c)

[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'e' b'l' b'c']


fromiter(iterable, dtype, count)
--------------------------------------------

* count = -1 by default (length of returned array)

In [15]:
list = [10,20,30,40,50]

In [16]:
d = np.fromiter(list,dtype='float',count=-1)
print(d)

[10. 20. 30. 40. 50.]


In [17]:
d = np.fromiter(list,dtype='S1',count=-1)
print(d)

[b'1' b'2' b'3' b'4' b'5']


In [19]:
d = np.fromiter(list,dtype='S2',count=2)
print(d)

[b'10' b'20']
