# ARRAYS WITH NUMERICAL RANGES

* ARANGE()
* LINSPACE()
* LOGSPACE()

* In all 3 functions we need to pass NUMERICAL RANGE. And it will returns array with value in given range and required datatype. "start index, stop index, dtype" are the common parameters in above functions.

arange(start index, stop index, step size, dtype)

In [1]:
import numpy as np

In [2]:
np.arange(0,10,2,dtype='int')

array([0, 2, 4, 6, 8])

In [3]:
arr = np.arange(0,10,2,dtype='int')
print(arr)

[0 2 4 6 8]


linespace(start index, stop index, num, endpoint, retstep, dtype)

* start index -> lower boundary values
* stop index -> upper boundary values
* num -> number of required values in array, oprional, default = 50
* endpoint -> TRUE - stop index will be included
              FALSE - stop index will not be included
              optional
              default = TRUE
* retstep -> Defference between values, optional
            TRUE - visible
            FALSE - not visible.
            default = FALSE

In [4]:
arr1 = np.linspace(0,10,5)
print(arr1)

[ 0.   2.5  5.   7.5 10. ]


In [9]:
arr1 = np.linspace(0,10)# by default 50 elements.
print(arr1)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [5]:
arr1 = np.linspace(0,10,5,endpoint=False)
print(arr1)

[0. 2. 4. 6. 8.]


In [7]:
arr1 = np.linspace(0,10,5,endpoint=False,retstep=True)
print(arr1)

(array([0., 2., 4., 6., 8.]), 2.0)


In [11]:
arr1 = np.linspace(0,10,20,endpoint=True,retstep=True,dtype='float')
print(arr1)

(array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]), 0.5263157894736842)


logspace()

logspace(start index, stop indes, num, end point, base, dtype)

* num -> no of values required, default = 50, optional
* base -> base of log value, default = 10, oprional

In [13]:
np.logspace(0,10,num = 4, endpoint=False)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07])

In [12]:
arr2 = np.logspace(0,10,num = 4, endpoint=False)
print(arr2)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07]


In [14]:
arr2 = np.logspace(0,10,num = 4, endpoint=False,base=2)
print(arr2)

[  1.           5.65685425  32.         181.01933598]


In [15]:
arr2 = np.logspace(0,10, endpoint=False, base=2) # by defult it will take 50 if we will not mention "num" 
print(arr2)

[  1.           1.14869835   1.31950791   1.51571657   1.74110113
   2.           2.29739671   2.63901582   3.03143313   3.48220225
   4.           4.59479342   5.27803164   6.06286627   6.96440451
   8.           9.18958684  10.55606329  12.12573253  13.92880901
  16.          18.37917368  21.11212657  24.25146506  27.85761803
  32.          36.75834736  42.22425314  48.50293013  55.71523605
  64.          73.51669472  84.44850629  97.00586026 111.4304721
 128.         147.03338944 168.89701258 194.01172051 222.8609442
 256.         294.06677888 337.79402516 388.02344103 445.72188841
 512.         588.13355776 675.58805032 776.04688205 891.44377682]


In [16]:
arr2 = np.logspace(0,10, endpoint=False,dtype='int')
print(arr2)

[          1           1           2           3           6          10
          15          25          39          63         100         158
         251         398         630        1000        1584        2511
        3981        6309       10000       15848       25118       39810
       63095      100000      158489      251188      398107      630957
     1000000     1584893     2511886     3981071     6309573    10000000
    15848931    25118864    39810717    63095734   100000000   158489319
   251188643   398107170   630957344  1000000000  1584893192 -2147483648
 -2147483648 -2147483648]
