* shape() -> return tuple specifying indices and no.of elements

In [2]:
import numpy as np

In [5]:
a = np.array([10,20,30,40,50,60])
print(a)
print(np.shape(a))

[10 20 30 40 50 60]
(6,)


In [6]:
a = np.array([[10,20,30],[40,50,60]])
print(a)
print(np.shape(a))

[[10 20 30]
 [40 50 60]]
(2, 3)


In [7]:
a = np.array([[10,20],[30,40],[50,60]])
print(a)
print(np.shape(a))

[[10 20]
 [30 40]
 [50 60]]
(3, 2)


* reshape(ArrayName, NewShapeDimensions)

In [8]:
a = np.array([10,20,30,40,50,60])

In [9]:
np.reshape(a,(3,2))

array([[10, 20],
       [30, 40],
       [50, 60]])

In [11]:
b = np.reshape(a,(2,3))
print(b)

[[10 20 30]
 [40 50 60]]


In [12]:
np.reshape(a,(3,4))

ValueError: cannot reshape array of size 6 into shape (3,4)

In [15]:
# changing shape of an existing array
a = np.array([[10,20],[30,40],[50,60]])
print(a)
print('--------')

b = np.reshape(a,(2,3))
print(b)

[[10 20]
 [30 40]
 [50 60]]
--------
[[10 20 30]
 [40 50 60]]


# Initialization functions

* zeros(shape, dtype)

In [16]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((4,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.zeros((4,4),dtype = 'int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

* ones(shape, dtype)

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

* full(shape,default value)

In [21]:
np.full((4,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

* eye(rows/columns, dtype) -> take square matrix, initializes 1's on all diagonal positions, initializes 0's on all non-diagonal positions 

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(4,dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])