# Accessing elements

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40,50,60])

In [3]:
print(a[1])

20


In [4]:
print(a[-1])

60


In [5]:
# 2D arrays

b = np.array([[10,20,30],[40,50,60]])

In [7]:
print(b[0,1])

20


In [8]:
# 3Dimentional array

c = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])

In [11]:
print(c[1,1,0])

100


In [14]:
print(c[-1,-1,-3])

100


In [18]:
print('1 Dimentional array','\n',a)
print('')
print('2 Dimentional array','\n',b)
print('')
print('3 Dimentional array','\n',c)

1 Dimentional array 
 [10 20 30 40 50 60]

2 Dimentional array 
 [[10 20 30]
 [40 50 60]]

3 Dimentional array 
 [[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


# SLICING OPERATION ON NDARRAY

In [19]:
a = np.array([10,20,30,40,50,60])

In [20]:
print(a[::])

[10 20 30 40 50 60]


In [21]:
print(a[1:4:2])

[20 40]


In [22]:
print(a[::2])

[10 30 50]


In [23]:
print(a[:2])

[10 20]


In [24]:
print(a[2:])

[30 40 50 60]


In [25]:
#2D array
print(b)

[[10 20 30]
 [40 50 60]]


In [29]:
print(b[1,0:2])

[40 50]


In [30]:
# 3D array
print(c)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [31]:
print(c[1,0,1:2])

[80]


In [33]:
print(c[-1,-2,-2:-1])

[80]


In [34]:
print(c[0:2,0:2,0:2])

[[[ 10  20]
  [ 40  50]]

 [[ 70  80]
  [100 110]]]
