Attribute to represent data type of an array is 'dtype'
* i - int
* f - float
* S - string
* U - unicode staring
* m - timedelta
* M - datetime
* O - object
* v - void

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,'a'])
print(a)
print(a.dtype)

['1' '2' 'a']
<U11


In [5]:
a = np.array([1,2])
print(a)
print(a.dtype)

[1 2]
int32


In [8]:
a = np.array([1,2,3],dtype='f')
print(a)
print(a.dtype)

[1. 2. 3.]
float32


In [10]:
x = a.astype('U')
print(x)

['1.0' '2.0' '3.0']


In [11]:
a = np.array([10,0,30,0,50])
print(a)
print(a.dtype)

b = a.astype('bool')
print(b)
print(b.dtype)

[10  0 30  0 50]
int32
[ True False  True False  True]
bool


# copy()

* External copy
* If any one element is modified then it will not reflect to another array
* Two arrays

In [18]:
a = np.array([1,2,4])
b = a.copy()

print('a=',a)
print('b=',b)
print('')
b[2] = 3
print('a=',a)
print('b=',b)

print(a.base)
print(b.base)

a= [1 2 4]
b= [1 2 4]

a= [1 2 4]
b= [1 2 3]
None
None


# view()

* Creats a reference to existing array
* If any one element is modified then it will be reflected on original array
* Only one array

In [19]:
a = np.array([1,2,4])
b = a.view()

print('a=',a)
print('b=',b)
print('')
b[2] = 3
print('a=',a)
print('b=',b)

print(a.base)
print(b.base)

a= [1 2 4]
b= [1 2 4]

a= [1 2 3]
b= [1 2 3]
None
[1 2 3]
