* split(array, no.of splits)
    no of splits -> equal division

In [2]:
import numpy as np

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
np.split(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [4]:
np.split(a,3)

ValueError: array split does not result in an equal division

* array_split(array,no.of splits)

In [5]:
np.array_split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

* hsplit()

In [6]:
np.hsplit(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

* vsplit()
    Not applicable for 1D array. Minimum of 2D Array is required to implement vsplit()

In [8]:
b = np.arange(6).reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [9]:
np.vsplit(b,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [11]:
v = np.vsplit(b,2)
print(v)

[array([[0, 1, 2]]), array([[3, 4, 5]])]
